- 설치
    - GPU가 있는 경우
        - conda install keras-gpu
        - conda install tensorflow-gpu (텐서플로우 경우)
    - 일반적인 경우
        - conda install kearas

- keras는 API 기반 인터페이스이다
- 엔진을 교체하고 싶다면
    - 사용자계정/.keras/keras.json
    {
        "floatx": "float32",
        "epsilon": 1e-07,
        "backend": "tensorflow",  <- 사용 엔진(프레임웍)
        "image_data_format": "channels_last"
    }

In [6]:
import keras

C:\Users\User\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


### 간단한 루틴으로 케라스 확인

In [2]:
import numpy

In [3]:
# 더미 데이터 구성
x = numpy.array( [0,1, 2, 3, 4] )

In [4]:
# 2:가중치
# 1:편향
y = x * 2 + 1

In [5]:
x, y

(array([0, 1, 2, 3, 4]), array([1, 3, 5, 7, 9]))

In [7]:
# 인공 신경망 모델링
# 인공 신경망을 만들기 시작했음을 알린다 (파이썬 프로세스에게)
model = keras.models.Sequential()

# add()를 이용하여 인공지능 계층(layer)를 추가
# 추가된 계층은 입력노드와 가중치등을 가지는 선형 처리 계층이다
model.add( keras.layers.Dense( 1, input_shape=(1, ) ) )

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
# 모델 학습 -> 최적화 알고리즘 : SGD, 손실함수 평균제곱근오차 : mse
model.compile( 'SGD', 'mse' )

In [9]:
# 훈련
# epochs : 인공신경망 학습시 학습 데이터 전체가 사용된 한세대, 반복회수, 세대수
# verbose : 학습 진행 사항의 표시 , 0:표시 않함
model.fit( x[:2], y[:2], epochs=1000, verbose=0 )

Instructions for updating:
Use tf.cast instead.


In [10]:
# 예측
model.predict( x[2:] ).flatten()

array([4.9501114, 6.914012 , 8.8779125], dtype=float32)

In [11]:
y[2:]

array([5, 7, 9])