In [2]:
import tensorflow as tf

In [3]:
hi = tf.constant('hello')
hi

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
sess = tf.Session()
sess.run( hi )

b'hello'

#### 텐서플로우를 이용한 간단한 계산

- 덧셈

In [6]:
# 상수 정의
a = tf.constant( 1234 )
b = tf.constant( 5000 )
a, b

(<tf.Tensor 'Const_3:0' shape=() dtype=int32>,
 <tf.Tensor 'Const_4:0' shape=() dtype=int32>)

In [8]:
# 계산 정의
add_op = a + b
add_op

<tf.Tensor 'add_1:0' shape=() dtype=int32>

- 텐서플로우는 덧셈이라는 계산을 정의만 할뿐, 변수에 add_op에 대입되는 것은
- 덧셈의 결과로 나오는 상수가 아니라 데이터 플로우 그래프라는 객체이다

In [9]:
# 세션을 시작
sess = tf.Session()

In [10]:
# 계산 처리는 파이썬이 하지 않고, 파이썬 외부 즉 텐서플로우에서 진행
# 계산 처리는 그래프라는 객체를 구축하고, 이러한 그래프르 텐서플로우가 
# 실행하면서  데이터를 흘러가는 구조이다
res = sess.run( add_op )
res, type(res)

(6234, numpy.int32)

#### 텐서플로우의 기본 항목

- 핵심 데이터 구조 요소 3개
 > 상수:Constant   
 > 변수:Variable    
 > 플레이스홀더:Placeholder    

In [12]:
# 상수 정의
a = tf.constant( 120, name='a' )
b = tf.constant( 130, name='b' )
c = tf.constant( 140, name='c' )

a, b, c

(<tf.Tensor 'a_1:0' shape=() dtype=int32>,
 <tf.Tensor 'b_1:0' shape=() dtype=int32>,
 <tf.Tensor 'c_1:0' shape=() dtype=int32>)

In [14]:
# 변수 정의
v = tf.Variable( 0, name='v' )
v, v.name

(<tf.Variable 'v_1:0' shape=() dtype=int32_ref>, 'v_1:0')

In [15]:
# 데이터 플로우 그래프 정의
calc_op = a + b + c
calc_op

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
# 변수에 값을 대입 => 데이터 플로우 그래프
assign_op = tf.assign( v, calc_op )
assign_op

<tf.Tensor 'Assign:0' shape=() dtype=int32_ref>

In [17]:
# 세션 실행
sess = tf.Session()
sess.run( assign_op )

390

In [19]:
# 변수값 출력하기 -> 세션 수행을 통해서 확인
v, sess.run( v )

(<tf.Variable 'v_1:0' shape=() dtype=int32_ref>, 390)

- 플레이스홀더
> 쿼리 수행할때, ? 기호 <= 이런 느낌  
> 데이터 플로우 그래프 구축시, 값을 넣지 않고, 값을 담을 수 있는 형태의 그릇만 만드는 형식 => 세션이 수행될때 값을 넣어서 실행   
> 템플릿과 유사하가 값을 넣어 두는 공간을 만드는 기능  

In [21]:
# 정수형 데이터를 3개를 담을수 있는 그릇(배열이용) 준비 => 플레이스 홀더를 준비
a = tf.placeholder( tf.int32, [3] )
a

<tf.Tensor 'Placeholder_1:0' shape=(3,) dtype=int32>

In [22]:
# 상수
b = tf.constant( 2 )

In [23]:
# 데이터 플로우 그래프
# 배열 * 값 => 행렬 * 값 => 백터 * 스칼라
x2_op = a * b

In [24]:
sess = tf.Session()

In [25]:
# 수행
# feed_dict는 플레이스 홀더에 값을 채운다
r1 = sess.run( x2_op, feed_dict={ a:[1,2,3] } )
r1

array([2, 4, 6])

#### 배열의 크기를 가변으로 처리하여 구성

In [26]:
# None을 넣으면 가변 처리가 되서, 배열의 개수는 가변적으로 대입 가능
# 플레이스 홀더 정의
a = tf.placeholder( tf.int32, [None] )

In [27]:
# 상수 정의
b = tf.constant( 10 )

In [28]:
# 데이터 플로우 그래프 정의
x10_op = a * b

In [29]:
sess = tf.Session()

In [30]:
sess.run( x10_op,  feed_dict={ a:[1,2,3,4,5] })

array([10, 20, 30, 40, 50])

In [31]:
sess.run( x10_op,  feed_dict={ a:[10,20] })

array([100, 200])